:teams:
- mob_a_team:
  :name: Mobile-order
  :department_id: 1
  :project_key: JMBMOB
  :board_id: 230
  :subteam: Mob-Order
  :deployment_constraint_id: 1
  :position: 0
- mob_baywatch:
  :name: Mobile-orientation
  :department_id: 1
  :project_key: JMBMOB
  :board_id: 231
  :subteam: Mob-Orientation
  :deployment_constraint_id: 1
  :position: 1000
- food_csi:
  :name: CSI
  :department_id: 1
  :project_key: FOOD
  :board_id: 294
  :subteam: CSI
  :deployment_constraint_id: 1
  :archived_at: 01-07-2019
- selling:
  :name: Selling
  :department_id: 1
  :project_key: SEL
  :board_id: 261
  :deployment_constraint_id: 3
  :position: 8000
- collect_pay_old:
  :name: Collect and Pay (Archived)
  :department_id: 1
  :project_key: OMS
  :board_id: 259
  :deployment_constraint_id: 3
  :position: 4000
  :archived_at: 10-03-2020
- collect_pay:
  :name: Collect and Pay
  :department_id: 1
  :project_key: OMS
  :board_id: 574
  :deployment_constraint_id: 3
  :position: 4000
  :started_at: 11-03-2020
- ordering:
  :name: Ordering (Archived)
  :department_id: 1
  :project_key: ORD
  :board_id: 260
  :deployment_constraint_id: 3
  :archived_at: 26-09-2019
- ordering_rc:
  :name: Ordering
  :department_id: 1
  :project_key: RC
  :board_id: 579
  :deployment_constraint_id: 3
  :position: 9000
- b2b:
  :name: B2B
  :department_id: 1
  :project_key: B2BJTC
  :board_id: 258
  :deployment_constraint_id: 3
  :position: 10000
- inspiration:
  :name: Inspiration
  :department_id: 1
  :project_key: INS
  :board_id: 228
  :deployment_constraint_id: 3
  :position: 7000
- winkelapp:
  :name: Winkelapp
  :department_id: 1
  :project_key: APP
  :board_id: 43
  :deployment_constraint_id: 4
  :archived_at: 31-12-2019
- find_it:
  :name: Finding
  :department_id: 1
  :project_key: FI
  :board_id: 267
  :deployment_constraint_id: 3
  :position: 15000
- smdx:
  :name: SMDX
  :department_id: 2
  :project_key: SAP2
  :board_id: 14
  :deployment_constraint_id: 6
- sap_marines:
  :name: Yellow SAP Marines
  :department_id: 2
  :project_key: SAP5
  :board_id: 199
  :deployment_constraint_id: 6
- musketiers:
  :name: FMCO team 2
  :department_id: 2
  :project_key: FMCO3
  :board_id: 309
  :deployment_constraint_id: 6
- pim:
  :name: Pim
  :department_id: 1
  :project_key: PIM
  :board_id: 466
  :deployment_constraint_id: 4
- esb:
  :name: ESB
  :department_id: 2
  :project_key: ESB
  :board_id: 626
  :deployment_constraint_id: 6
- sc_core:
  :name: SC Core systems
  :department_id: 2
  :project_key: SCC
  :board_id: 301
  :deployment_constraint_id: 4
- sap_1:
  :name: SAP1 SCM
  :department_id: 2
  :project_key: SAP1
  :board_id: 312
  :deployment_constraint_id: 6
- ps:
  :name: Performance & Stability
  :department_id: 1
  :project_key: PS
  :board_id: 427
  :deployment_constraint_id: 3
  :archived_at: 01-02-2020
- ish_upgrade:
  :name: Intershop Upgrade
  :department_id: 1
  :project_key: UI
  :board_id: 287
  :deployment_constraint_id: 3
  :archived_at: 01-12-2019
- prometheus:
  :name: Prometheus
  :department_id: 3
  :project_key: BI5
  :board_id: 240
  :deployment_constraint_id: 6
- transformers:
  :name: Transformers
  :department_id: 3
  :project_key: BI6
  :board_id: 281
  :deployment_constraint_id: 6
- r10:
  :name: Store-1 R10
  :department_id: 3
  :project_key: SAP4
  :board_id: 18
  :deployment_constraint_id: 4
- cloudbusters:
  :name: Cloud Busters
  :department_id: 3
  :project_key: JAF
  :board_id: 353
  :deployment_constraint_id: 3
- dotcomdots:
  :name: Dotcom Dots
  :department_id: 3
  :project_key: STL
  :board_id: 192
  :deployment_constraint_id: 6
- iam:
  :name: IAM
  :department_id: 3
  :project_key: IAMD
  :board_id: 405
  :deployment_constraint_id: 6
- sap_finance:
  :name: SAP Finance
  :department_id: 2
  :project_key: SAP3
  :board_id: 141
  :deployment_constraint_id: 6
- rpa:
  :name: RPA
  :department_id: 2
  :project_key: FN
  :board_id: 470
  :deployment_constraint_id: 6
- bi1:
  :name: BI One
  :department_id: 3
  :board_id: 16
  :project_key: BI1
  :deployment_constraint_id: 6
- bi2:
  :name: Trailblazers
  :department_id: 3
  :board_id: 8
  :project_key: BI2
  :deployment_constraint_id: 6
- bi3:
  :name: BI Three
  :department_id: 3
  :board_id: 97
  :project_key: BI3
  :deployment_constraint_id: 6
- mob_csi:
  :name: Mobile-inspiration
  :department_id: 1
  :board_id: 535
  :project_key: JMBMOB
  :deployment_constraint_id: 1
  :subteam: Mob-Inspiration
  :position: 2000
- loyal:
  :name: Loyal
  :department_id: 1
  :board_id: 201
  :project_key: HJ
  :deployment_constraint_id: 3
  :position: 5000
- medewerker_app:
  :name: Employee
  :department_id: 1
  :board_id: 336
  :project_key: MA
  :deployment_constraint_id: 1
  :position: 13000
  :started_at: 11-03-2020
- service_platform:
  :name: Aftercare
  :department_id: 1
  :board_id: 489
  :project_key: SP
  :deployment_constraint_id: 3
  :position: 12000
  :started_at: 11-03-2020
- predict_it:
  :name: Predict IT
  :department_id: 1
  :board_id: 348
  :project_key: PI
  :deployment_constraint_id: 3
  :position: 6000
- mdm:
  :name: MDM
  :department_id: 2
  :board_id: 484
  :project_key: MDM
  :deployment_constraint_id: 6
- foodcoach_cust:
  :name: Foodcoach
  :department_id: 1
  :board_id: 591
  :project_key: FDCCH
  :deployment_constraint_id: 1
  :position: 14000
- cust_profile:
  :name: Customer Profile
  :department_id: 1
  :board_id: 615
  :project_key: CPR
  :deployment_constraint_id: 3
  :position: 11000
- intershop:
  :name: Intershop
  :department_id: 1
  :board_id: 606
  :project_key: ISH
  :deployment_constraint_id: 3
  :position: 3000
  :started_at: 11-01-2020
- xecm_opentext:
  :name: Open Tekst
  :department_id: 2
  :board_id: 526
  :project_key: XECM
  :deployment_constraint_id: 6
- aps_hd:
  :name: APS HD
  :department_id: 1
  :board_id: 644
  :project_key: APSHD
  :deployment_constraint_id: 3
- lp_bi:
  :name: LP BI
  :department_id: 3
  :board_id: 621
  :project_key: LPBI
  :deployment_constraint_id: 6
:departments:
- digital:
  :name: JTC Digital
  :id: 1
- core:
  :name: JTC Core
  :id: 2
- data:
  :name: JTC Data & Store
  :id: 3
:deployment_constraints:
- app_deploy:
  :id: 1
  :name: App deploy
- cab:
  :id: 2
  :name: CAB
- no_constraint:
  :id: 3
  :name: No constraint
- supplier:
  :id: 4
  :name: Supplier bound
- exclude:
  :id: 5
  :name: Exclude from reporting
- cap:
  :id: 6
  :name: CAP
:quarters:
- q1_2019:
  :id: 1
  :start_week: 1
  :end_week: 16
  :year: 2019
  :fix_version: Q1 2019 plan
- q2_2019:
  :id: 2
  :start_week: 17
  :end_week: 28
  :year: 2019
  :fix_version: Q2 2019 plan
- q3_2019:
  :id: 3
  :start_week: 29
  :end_week: 40
  :year: 2019
  :fix_version: Q3 2019 plan
- q4_2019:
  :id: 4
  :start_week: 41
  :end_week: 52
  :year: 2019
  :fix_version: Q4 2019 plan
- q1_2020:
  :id: 5
  :start_week: 1
  :end_week: 16
  :year: 2020
  :fix_version: Q1 2020 plan
- q2_2020:
  :id: 6
  :start_week: 17
  :end_week: 28
  :year: 2020
  :fix_version: Q2 2020 plan
- q3_2020:
  :id: 7
  :start_week: 29
  :end_week: 40
  :year: 2020
  :fix_version: Q3 2020 plan
- q4_2020:
  :id: 8
  :start_week: 41
  :end_week: 52
  :year: 2020
  :fix_version: Q4 2020 plan
