:teams:
- mob_a_team:
  :id: 1
  :name: Mobile-order
  :department_id: 1
  :board_id: 230
  :subteam: Mob-Order
  :deployment_constraint_id: 1
  :position: 0
- mob_baywatch:
  :id: 2
  :name: Mobile-orientation
  :department_id: 1
  :board_id: 231
  :subteam: Mob-Orientation
  :deployment_constraint_id: 1
  :position: 1000
- food_csi:
  :id: 3
  :name: CSI
  :department_id: 1
  :board_id: 294
  :subteam: CSI
  :deployment_constraint_id: 1
  :archived_at: 01-07-2019
- selling:
  :id: 4
  :name: Selling
  :department_id: 1
  :board_id: 261
  :deployment_constraint_id: 3
  :position: 8000
- collect_pay_old:
  :id: 5
  :name: Collect and Pay (Archived)
  :department_id: 1
  :board_id: 259
  :deployment_constraint_id: 3
  :position: 4000
  :archived_at: 10-03-2020
- collect_pay:
  :id: 6
  :name: Collect and Pay
  :department_id: 1
  :board_id: 574
  :deployment_constraint_id: 3
  :position: 4000
  :started_at: 11-03-2020
- ordering:
  :id: 7
  :name: Ordering (Archived)
  :department_id: 1
  :board_id: 260
  :deployment_constraint_id: 3
  :archived_at: 26-09-2019
- ordering_rc:
  :id: 8
  :name: Ordering
  :department_id: 1
  :board_id: 579
  :deployment_constraint_id: 3
  :position: 11000
- b2b:
  :id: 9
  :name: B2B
  :department_id: 1
  :board_id: 258
  :deployment_constraint_id: 3
  :position: 10000
- inspiration:
  :id: 10
  :name: Inspiration
  :department_id: 1
  :board_id: 228
  :deployment_constraint_id: 3
  :position: 7000
- winkelapp:
  :id: 11
  :name: Winkelapp
  :department_id: 1
  :board_id: 43
  :deployment_constraint_id: 4
  :archived_at: 31-12-2019
- find_it:
  :id: 12
  :name: Search
  :department_id: 1
  :board_id: 267
  :deployment_constraint_id: 3
  :position: 17000
- smdx:
  :id: 13
  :name: SMDX
  :department_id: 2
  :board_id: 14
  :deployment_constraint_id: 6
  :position: 19000
- sap_marines:
  :id: 14
  :name: Yellow SAP Marines
  :department_id: 2
  :board_id: 199
  :deployment_constraint_id: 6
- musketiers:
  :id: 15
  :name: SLTS
  :department_id: 2
  :board_id: 309
  :deployment_constraint_id: 6
  :position: 20000
- pim:
  :id: 16
  :name: Pim
  :department_id: 1
  :board_id: 466
  :deployment_constraint_id: 4
  :position: 18000
- esb:
  :id: 17
  :name: Integration
  :department_id: 2
  :board_id: 626
  :deployment_constraint_id: 6
  :position: 24000
- sc_core:
  :id: 18
  :name: SC Core systems
  :department_id: 2
  :board_id: 301
  :deployment_constraint_id: 4
  :position: 28000
- juscia:
  :id: 19
  :name: JuSCIA
  :department_id: 2
  :board_id: 312
  :deployment_constraint_id: 6
  :position: 26000
  :filter_sprints_by_team_name: true
- scrumbled_eggs:
  :id: 20
  :name: SRUMbled Eggs
  :department_id: 2
  :board_id: 312
  :deployment_constraint_id: 6
  :position: 26500
  :filter_sprints_by_team_name: true
- sap_scone:
  :id: 21
  :name: SAP SCONE
  :department_id: 2
  :board_id: 312
  :deployment_constraint_id: 6
  :position: 26750
  :filter_sprints_by_team_name: true
- ps:
  :id: 22
  :name: Performance & Stability
  :department_id: 1
  :board_id: 427
  :deployment_constraint_id: 3
  :archived_at: 01-02-2020
- ish_upgrade:
  :id: 23
  :name: Intershop Upgrade
  :department_id: 1
  :board_id: 287
  :deployment_constraint_id: 3
  :archived_at: 01-12-2019
- prometheus:
  :id: 24
  :name: Prometheus
  :department_id: 3
  :board_id: 240
  :deployment_constraint_id: 6
  :position: 37000
- transformers:
  :id: 25
  :name: Transformers
  :department_id: 3
  :board_id: 281
  :deployment_constraint_id: 6
  :position: 38000
- r10:
  :id: 26
  :name: R10 core
  :department_id: 3
  :board_id: 396
  :deployment_constraint_id: 4
  :component: Core Team
  :position: 39000
- r10_extend:
  :id: 27
  :name: R10 extendables
  :department_id: 3
  :board_id: 395
  :deployment_constraint_id: 4
  :component: Extension Team
  :position: 40000
- cloudbusters:
  :id: 28
  :name: Cloud Busters
  :department_id: 3
  :board_id: 353
  :deployment_constraint_id: 3
  :position: 41000
- dotcomdots:
  :id: 29
  :name: .NET
  :department_id: 3
  :board_id: 192
  :deployment_constraint_id: 6
  :position: 42000
- iam:
  :id: 30
  :name: ID
  :department_id: 3
  :board_id: 405
  :deployment_constraint_id: 6
  :position: 43000
- sap_finance_1:
  :id: 31
  :name: Finance Team 1
  :department_id: 2
  :board_id: 141
  :deployment_constraint_id: 6
  :position: 30000
  :filter_sprints_by_team_name: true
- rpa:
  :id: 32
  :name: RPA
  :department_id: 2
  :board_id: 470
  :deployment_constraint_id: 6
  :position: 31000
- bi1:
  :id: 33
  :name: BI One
  :department_id: 3
  :board_id: 16
  :deployment_constraint_id: 6
  :position: 33000
- bi2:
  :id: 34
  :name: Trailblazers
  :department_id: 3
  :board_id: 8
  :deployment_constraint_id: 6
  :position: 34000
- bi3:
  :id: 35
  :name: BI Three
  :department_id: 3
  :board_id: 97
  :deployment_constraint_id: 6
  :position: 35000
- mob_csi:
  :id: 36
  :name: Mobile-inspiration
  :department_id: 1
  :board_id: 535
  :deployment_constraint_id: 1
  :subteam: Mob-Inspiration
  :position: 2000
- loyal:
  :id: 37
  :name: Loyal
  :department_id: 1
  :board_id: 201
  :deployment_constraint_id: 3
  :position: 5000
- medewerker_app:
  :id: 38
  :name: Employee
  :department_id: 1
  :board_id: 336
  :deployment_constraint_id: 1
  :position: 13000
  :started_at: 11-03-2020
- service_platform:
  :id: 39
  :name: Aftercare
  :department_id: 1
  :board_id: 489
  :deployment_constraint_id: 3
  :position: 12000
  :started_at: 11-03-2020
- predict_it:
  :id: 40
  :name: Predict IT
  :department_id: 1
  :board_id: 348
  :deployment_constraint_id: 3
  :position: 44000
- mdm:
  :id: 41
  :name: MDM EBX5
  :department_id: 2
  :board_id: 484
  :deployment_constraint_id: 6
  :position: 21000
- foodcoach_cust:
  :id: 42
  :name: Foodcoach
  :department_id: 1
  :board_id: 591
  :deployment_constraint_id: 1
  :position: 15000
- foodcoach_pro:
  :id: 43
  :name: Foodcoach Pro
  :department_id: 1
  :board_id: 620
  :deployment_constraint_id: 1
  :position: 16000
- cust_profile:
  :id: 44
  :name: Customer Profile
  :department_id: 1
  :board_id: 615
  :deployment_constraint_id: 3
  :position: 9000
- intershop:
  :id: 45
  :name: Intershop
  :department_id: 1
  :board_id: 606
  :deployment_constraint_id: 3
  :position: 3000
  :started_at: 11-01-2020
- xecm_opentext:
  :id: 46
  :name: JCA Open Tekst
  :department_id: 2
  :board_id: 526
  :deployment_constraint_id: 6
  :position: 25000
- aps_hd:
  :id: 47
  :name: APS HD
  :department_id: 1
  :board_id: 644
  :deployment_constraint_id: 3
  :position: 11000
- lp_bi:
  :id: 48
  :name: LP BI
  :department_id: 3
  :board_id: 621
  :deployment_constraint_id: 6
- laplace:
  :id: 49
  :name: La Place IT
  :department_id: 1
  :board_id: 450
  :deployment_constraint_id: 3
  :position: 14000
- jda:
  :id: 50
  :name: JDA
  :department_id: 2
  :board_id: 674
  :deployment_constraint_id: 6
  :position: 22000
- optumera:
  :id: 51
  :name: Optumera
  :department_id: 2
  :board_id: 676
  :deployment_constraint_id: 6
  :position: 23000
- aps_sc:
  :id: 52
  :name: APS
  :department_id: 2
  :board_id: 622
  :deployment_constraint_id: 6
  :position: 29000
- hr:
  :id: 53
  :name: HR/WFM
  :department_id: 2
  :board_id: 332
  :deployment_constraint_id: 6
  :position: 32000
- bi_beheer:
  :id: 54
  :name: BI Beheer
  :department_id: 3
  :board_id: 334
  :deployment_constraint_id: 6
  :position: 36000
- sap_finance_a:
  :id: 55
  :name: Finance Team A
  :department_id: 2
  :board_id: 141
  :deployment_constraint_id: 6
  :position: 35000
  :filter_sprints_by_team_name: true
:departments:
- digital:
  :name: JTC Digital
  :id: 1
- core:
  :name: JTC Core
  :id: 2
- data:
  :name: JTC Data & Store
  :id: 3
:deployment_constraints:
- app_deploy:
  :id: 1
  :name: App deploy
- cab:
  :id: 2
  :name: CAB
- no_constraint:
  :id: 3
  :name: No constraint
- supplier:
  :id: 4
  :name: Supplier bound
- exclude:
  :id: 5
  :name: Exclude from reporting
- cap:
  :id: 6
  :name: CAP
:quarters:
- q1_2019:
  :id: 1
  :start_week: 1
  :end_week: 16
  :year: 2019
  :fix_version: Q1 2019 plan
- q2_2019:
  :id: 2
  :start_week: 17
  :end_week: 28
  :year: 2019
  :fix_version: Q2 2019 plan
- q3_2019:
  :id: 3
  :start_week: 29
  :end_week: 40
  :year: 2019
  :fix_version: Q3 2019 plan
- q4_2019:
  :id: 4
  :start_week: 41
  :end_week: 52
  :year: 2019
  :fix_version: Q4 2019 plan
- q1_2020:
  :id: 5
  :start_week: 1
  :end_week: 16
  :year: 2020
  :fix_version: Q1 2020 plan
- q2_2020:
  :id: 6
  :start_week: 17
  :end_week: 28
  :year: 2020
  :fix_version: Q2 2020 plan
- q3_2020:
  :id: 7
  :start_week: 29
  :end_week: 40
  :year: 2020
  :fix_version: Q3 2020 plan
- q4_2020:
  :id: 8
  :start_week: 41
  :end_week: 52
  :year: 2020
  :fix_version: Q4 2020 plan
