:use_cached_data: true
:number_of_cached_sprints: 14
:teams:
- mob_a_team:
  :name: Mobile-order
  :department_id: 1
  :project_key: JMBMOB
  :board_id: 230
  :subteam: A-team
  :deployment_constraint_id: 1
- mob_baywatch:
  :name: Mobile-orientation
  :department_id: 1
  :project_key: JMBMOB
  :board_id: 231
  :subteam: Baywatch
  :deployment_constraint_id: 1
- food_csi:
  :name: CSI
  :department_id: 1
  :project_key: FOOD
  :board_id: 294
  :subteam: CSI
  :deployment_constraint_id: 1
- selling:
  :name: Selling
  :department_id: 1
  :project_key: SEL
  :board_id: 261
  :deployment_constraint_id: 3
- collect_pay:
  :name: Collect & pay
  :department_id: 1
  :project_key: OMS
  :board_id: 259
  :deployment_constraint_id: 3
- ordering:
  :name: Ordering
  :department_id: 1
  :project_key: ORD
  :board_id: 260
  :deployment_constraint_id: 3
- b2b:
  :name: B2B
  :department_id: 1
  :project_key: B2BJTC
  :board_id: 258
  :deployment_constraint_id: 3
- inspiration:
  :name: Inspiration
  :department_id: 1
  :project_key: INS
  :board_id: 228
  :deployment_constraint_id: 3
- winkelapp:
  :name: Winkelapp
  :department_id: 1
  :project_key: APP
  :board_id: 43
  :deployment_constraint_id: 4
- find_it:
  :name: Find it
  :department_id: 1
  :project_key: FI
  :board_id: 267
  :deployment_constraint_id: 3
- optimize_prime:
  :name: Optimize Prime
  :department_id: 1
  :project_key: RJC
  :board_id: 217
  :deployment_constraint_id: 3
- smdx:
  :name: SMDX
  :department_id: 2
  :project_key: SAP2
  :board_id: 14
  :deployment_constraint_id: 2
- sap_marines:
  :name: SAP Marines
  :department_id: 2
  :project_key: SAP5
  :board_id: 199
  :deployment_constraint_id: 2
- musketiers:
  :name: Musketiers
  :department_id: 2
  :project_key: FMCO3
  :board_id: 309
  :deployment_constraint_id: 2
- pim:
  :name: Pim
  :department_id: 1
  :project_key: PIM
  :board_id: 262
  :deployment_constraint_id: 4
- xecm:
  :name: xECM
  :department_id: 2
  :project_key: XECM
  :board_id: 526
  :deployment_constraint_id: 2
- esb:
  :name: ESB
  :department_id: 2
  :project_key: ESB
  :board_id: 168
  :deployment_constraint_id: 2
- sc_core:
  :name: SC Core systems
  :department_id: 2
  :project_key: SCC
  :board_id: 301
  :deployment_constraint_id: 2
- sap_1:
  :name: SAP1 SCM
  :department_id: 2
  :project_key: SAP1
  :board_id: 312
  :deployment_constraint_id: 2
- ps:
  :name: Performance & Stability
  :department_id: 1
  :project_key: PS
  :board_id: 427
  :deployment_constraint_id: 3
- enablers:
  :name: Enablers
  :department_id: 1
  :project_key: EN
  :board_id: 306
  :deployment_constraint_id: 3
- cloud:
  :name: Cloud Team
  :department_id: 1
  :project_key: CP
  :board_id: 344
  :deployment_constraint_id: 3
- ish_upgrade:
  :name: Intershop Upgrade
  :department_id: 1
  :project_key: UI
  :board_id: 287
  :deployment_constraint_id: 3
- prometheus:
  :name: Prometheus
  :department_id: 3
  :project_key: BI5
  :board_id: 240
  :deployment_constraint_id: 2
- transformers:
  :name: Transformers
  :department_id: 3
  :project_key: BI6
  :board_id: 281
  :deployment_constraint_id: 2
- r10:
  :name: Store-1 R10
  :department_id: 3
  :project_key: SAP4
  :board_id: 18
  :deployment_constraint_id: 2
- cloudbusters:
  :name: Cloud Busters
  :department_id: 3
  :project_key: JAF
  :board_id: 353
  :deployment_constraint_id: 2
- dotcomdots:
  :name: Dotcom Dots
  :department_id: 3
  :project_key: STL
  :board_id: 192
  :deployment_constraint_id: 2
- iam:
  :name: IAM
  :department_id: 3
  :project_key: IAMD
  :board_id: 405
  :deployment_constraint_id: 2
- sap_finance:
  :name: SAP Finance
  :department_id: 2
  :project_key: SAP3
  :board_id: 141
  :deployment_constraint_id: 2
- rpa:
  :name: RPA
  :department_id: 2
  :project_key: FN
  :board_id: 470
  :deployment_constraint_id: 2
- bi1:
  :name: BI One
  :department_id: 3
  :board_id: 16
  :project_key: BI1
  :deployment_constraint_id: 2
- bi2:
  :name: BI Trailblazers
  :department_id: 3
  :board_id: 8
  :project_key: BI2
  :deployment_constraint_id: 2
- bi3:
  :name: BI3
  :department_id: 3
  :board_id: 97
  :project_key: BI3
  :deployment_constraint_id: 2
- mob_csi:
  :name: Mobile-inspiration
  :department_id: 1
  :board_id: 535
  :project_key: JMBMOB
  :deployment_constraint_id: 1
  :subteam: CSI
- mob_all:
  :name: Mobile (all teams)
  :department_id: 1
  :board_id: 229
  :project_key: JMBMOB
  :deployment_constraint_id: 5
- loyal:
  :name: Loyal team
  :department_id: 1
  :board_id: 518
  :project_key: HJ
  :deployment_constraint_id: 3
- medewerker_app:
  :name: Medewerker app
  :department_id: 1
  :board_id: 336
  :project_key: MA
  :deployment_constraint_id: 1
- service_platform:
  :name: Service platform
  :department_id: 1
  :board_id: 489
  :project_key: SP
  :deployment_constraint_id: 3
- predict_it:
  :name: Predict it
  :department_id: 1
  :board_id: 348
  :project_key: PI
  :deployment_constraint_id: 3
:departments:
- digital:
  :name: JTC Digital
  :id: 1
- core:
  :name: JTC Core
  :id: 2
- data:
  :name: JTC Data & Store
  :id: 3
:deployment_constraints:
- app_deploy:
  :id: 1
  :name: App deploy
- cab:
  :id: 2
  :name: CAB
- no_constraint:
  :id: 3
  :name: No constraint
- supplier:
  :id: 4
  :name: Supplier bound
- exclude:
  :id: 5
  :name: Exclude from reporting
:issue_collections:
- p1_2019:
  :id: 1
  :name: P1 issues 2019
  :jira_filter: 24279
- jdd:
  :id: 2
  :name: JTC Digital Deployment issues 2019
  :jira_filter: 24369
- portfolio:
  :id: 3
  :name: Portfolio epics 2019
  :jira_filter: 24445
:quarters:
- q1_2019:
  :start_week: 1
  :end_week: 16
  :fix_version: Q1 2019 plan
- q2_2019:
  :start_week: 17
  :end_week: 28
  :fix_version: Q2 2019 plan
- q3_2019:
  :start_week: 29
  :end_week: 40
  :fix_version: Q3 2019 plan
- q4_2019:
  :start_week: 41
  :end_week: 52
  :fix_version: Q4 2019 plan
