apiVersion: apps/v1
kind: Deployment
metadata:
  name: {APP}
  namespace: {APP}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {APP}
  template:
    metadata:
      labels:
        app: {APP}
    spec:
      containers:
      - image: {CONTAINER_IMAGE}
        name: {APP}
        env:
        - name: JIRA_USERNAME
          valueFrom:
            secretKeyRef:
              name: jtc-jira
              key: JIRA_USERNAME
        - name: JIRA_API_KEY
          valueFrom:
            secretKeyRef:
              name: jtc-jira
              key: JIRA_API_KEY
        - name: JIRA_SITE
          valueFrom:
            secretKeyRef:
              name: jtc-jira
              key: JIRA_SITE
        - name: JIRA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: jtc-jira
              key: JIRA_CLIENT_ID
        - name: JIRA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: jtc-jira
              key: JIRA_CLIENT_SECRET
        - name: REDIS_HOST
          value: "master.dev-jtc-jira.h76mdt.euc1.cache.amazonaws.com"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jtc-jira
              key: redis_password
        - name: RAILS_RELATIVE_URL_ROOT
          value: "/jira"
        - name: URL_PREFIX
          value: "/jira"
        - name: RAILS_ENV
          value: "production"
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: RAILS_MASTER_KEY
          value: "237dd1fee65d1b2fcf463c446daa16e6"
        - name: STATSD_HOST
          value: "dogstatsd.datadog.svc.cluster.local"
        - name: APP_URL
          value: "https://internal.dev.cloud.jumbo.com/jira"
        ports:
        - containerPort: 3001
          name: {APP}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {APP}
  namespace: {APP}
spec:
  schedule: "15 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: {CONTAINER_IMAGE}
            name: {APP}
            command: ["/bin/bash"]
            args: ["-c", "thor cache:all"]
            env:
            - name: JIRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: jtc-jira
                  key: JIRA_USERNAME
            - name: JIRA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jtc-jira
                  key: JIRA_API_KEY
            - name: JIRA_SITE
              valueFrom:
                secretKeyRef:
                  name: jtc-jira
                  key: JIRA_SITE
            - name: JIRA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jtc-jira
                  key: JIRA_CLIENT_ID
            - name: JIRA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jtc-jira
                  key: JIRA_CLIENT_SECRET
            - name: REDIS_HOST
              value: "master.dev-jtc-jira.h76mdt.euc1.cache.amazonaws.com"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jtc-jira
                  key: redis_password
            - name: RAILS_RELATIVE_URL_ROOT
              value: "/jira"
            - name: URL_PREFIX
              value: "/jira"
            - name: RAILS_ENV
              value: "production"
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"
            - name: RAILS_MASTER_KEY
              value: "237dd1fee65d1b2fcf463c446daa16e6"
            - name: STATSD_HOST
              value: "dogstatsd.datadog.svc.cluster.local"
          restartPolicy: OnFailure
