version: '3.6'

services:
  web:
    build: .
    depends_on:
      - redis
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "rm -f /app/tmp/pids/server.pid; bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - 3001:3001
  redis:
    image: redis:alpine
    volumes:
      - redis:/data
  thor_runner:
    build:
      context: .
      dockerfile: ./thor/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "thor cache:all"
  redis_commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
 
volumes:
  redis:
