apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx-internal
  name: {APP}
  namespace: {APP}
spec:
  rules:
  - host: {FQDN}
    http:
      paths:
      - path: /{ING_PATH}
        backend:
          serviceName: {APP}
          servicePort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: {APP}
  namespace: {APP}
spec:
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: {APP}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {APP}
spec:
  ports:
  - port: 6379
  selector:
    app: redis
  type: ClusterIP
